package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * FaxEmployee generated by hbm2java
 */
@Entity
@Table(name = "faxEmployee", schema = "public")
public class FaxEmployee implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int faxEmployeeId;
	private String number;
	private Collection<Employee> employees;

	public FaxEmployee() {
	}

	public FaxEmployee(String number) {
		this.number = number;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "faxEmployeeId", unique = true, nullable = false)
	public int getFaxEmployeeId() {
		return this.faxEmployeeId;
	}

	public void setFaxEmployeeId(int faxEmployeeId) {
		this.faxEmployeeId = faxEmployeeId;
	}

	@Column(name = "number")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "faxEmployees")
	public Collection<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Collection<Employee> employees) {
		this.employees = employees;
	}

}
