package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FaxLocal generated by hbm2java
 */
@Entity
@Table(name = "faxLocal", schema = "public")
public class FaxLocal implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int faxLocalId;
	private Local local;
	private String number;

	public FaxLocal() {
		
	}

	public FaxLocal(String number) {
		this.number = number;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "faxLocalId", unique = true, nullable = false)
	public int getFaxLocalId() {
		return this.faxLocalId;
	}

	public void setFaxLocalId(int faxLocalId) {
		this.faxLocalId = faxLocalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "localId")
	public Local getLocal() {
		return this.local;
	}

	public void setLocal(Local local) {
		this.local = local;
	}

	@Column(name = "number")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

}
