package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Store;

/**
 * Gouvernorat generated by hbm2java
 */
@Entity
@Table(name = "gouvernorat", schema = "public")
public class Gouvernorat implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int gouvernoratId;
	private String code;
	private String latinName;
	private String arabicName;
	private Collection<Municipality> municipalities;
	private Collection<Delegation> delegations;

	public Gouvernorat() {
	}

	public Gouvernorat(String code, String latinName, String arabicName) {
		this.code = code;
		this.latinName = latinName;
		this.arabicName = arabicName;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "gouvernoratId", unique = true, nullable = false)
	public int getGouvernoratId() {
		return this.gouvernoratId;
	}

	public void setGouvernoratId(int gouvernoratId) {
		this.gouvernoratId = gouvernoratId;
	}

	@Column(name = "code", length = 254)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "latinName", length = 254)
	@Field(index=Index.YES, analyze=Analyze.YES, store=Store.YES)
	public String getLatinName() {
		return this.latinName;
	}

	public void setLatinName(String latinName) {
		this.latinName = latinName;
	}

	@Column(name = "arabicName", length = 254)
	@Field(index=Index.YES, analyze=Analyze.YES, store=Store.YES)
	public String getArabicName() {
		return this.arabicName;
	}

	public void setArabicName(String arabicName) {
		this.arabicName = arabicName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gouvernorat")
	public Collection<Municipality> getMunicipalities() {
		return this.municipalities;
	}

	public void setMunicipalities(Collection<Municipality> municipalities) {
		this.municipalities = municipalities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gouvernorat")
	public Collection<Delegation> getDelegations() {
		return this.delegations;
	}

	public void setDelegations(Collection<Delegation> delegations) {
		this.delegations = delegations;
	}

}
