package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MailEmployee generated by hbm2java
 */
@Entity
@Table(name = "mailEmployee", schema = "public")
public class MailEmployee implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int mailEmployeeId;
	private Employee employee;
	private String adress;

	public MailEmployee() {
	
	}

	public MailEmployee(String adress) {
		this.adress = adress;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "mailEmployeeId", unique = true, nullable = false)
	public int getMailEmployeeId() {
		return this.mailEmployeeId;
	}

	public void setMailEmployeeId(int mailEmployeeId) {
		this.mailEmployeeId = mailEmployeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeeId")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "adress")
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

}
