package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * MailStructure generated by hbm2java
 */
@Entity
@Table(name = "mailStructure", schema = "public")
public class MailStructure implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int mailStructureId;
	private String adress;
	private Collection<Structure> structures;

	public MailStructure() {
	}

	public MailStructure(String adress) {
		this.adress = adress;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "mailStructureId", unique = true, nullable = false)
	public int getMailStructureId() {
		return this.mailStructureId;
	}

	public void setMailStructureId(int mailStructureId) {
		this.mailStructureId = mailStructureId;
	}

	@Column(name = "adress", length = 254)
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "mailStructures")
	public Collection<Structure> getStructures() {
		return this.structures;
	}

	public void setStructures(Collection<Structure> structures) {
		this.structures = structures;
	}

}
