package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhoneLocal generated by hbm2java
 */
@Entity
@Table(name = "phoneLocal", schema = "public")
public class PhoneLocal implements Serializable {

	private int phoneLocalId;
	private Local local;
	private String number;
	private String typePhone;

	public PhoneLocal() {
	
	}

	public PhoneLocal(String number) {
		this.number = number;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "phoneLocalId", unique = true, nullable = false)
	public int getPhoneLocalId() {
		return this.phoneLocalId;
	}

	public void setPhoneLocalId(int phoneLocalId) {
		this.phoneLocalId = phoneLocalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "localId")
	public Local getLocal() {
		return this.local;
	}

	public void setLocal(Local local) {
		this.local = local;
	}

	@Column(name = "number")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}
	
	@Column(name = "typePhone")
	public String getTypePhone() {
		return this.typePhone;
	}

	public void setTypePhone(String typePhone) {
		this.typePhone = typePhone;
	}
}
