package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * PhoneEmployee generated by hbm2java
 */
@Entity
@Table(name = "phoneEmployee", schema = "public")
public class PhoneEmployee implements Serializable {

	private int phoneEmployeeId;
	private String number;
	private Collection<Employee> employees;

	public PhoneEmployee() {
	}

	public PhoneEmployee(String number) {
		this.number = number;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "phoneEmployeeId", unique = true, nullable = false)
	public int getPhoneEmployeeId() {
		return this.phoneEmployeeId;
	}

	public void setPhoneEmployeeId(int phoneEmployeeId) {
		this.phoneEmployeeId = phoneEmployeeId;
	}

	@Column(name = "number")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "phoneEmployees")
	public Collection<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Collection<Employee> employees) {
		this.employees = employees;
	}

}
