package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "positions", schema = "public")
public class Position implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int positionId;
	private String code;
	private String latinName;
	private String arabicName;
	private Collection<SubPosition> subPositions;

	public Position() {
		
	}

	public Position(String code, String latinName, String arabicName) {
		this.code = code;
		this.latinName = latinName;
		this.arabicName = arabicName;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "positionId", unique = true, nullable = false)
	public int getPositionId() {
		return this.positionId;
	}

	public void setPositionId(int positionId) {
		this.positionId = positionId;
	}

	@Column(name = "code", length = 254)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "latinName", length = 254)
	public String getLatinName() {
		return this.latinName;
	}

	public void setLatinName(String latinName) {
		this.latinName = latinName;
	}

	@Column(name = "arabicName", length = 254)
	public String getArabicName() {
		return this.arabicName;
	}

	public void setArabicName(String arabicName) {
		this.arabicName = arabicName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
	public Collection<SubPosition> getSubPositions() {
		return this.subPositions;
	}

	public void setSubPositions(Collection<SubPosition> subPositions) {
		this.subPositions = subPositions;
	}

}
