package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * SocialNetwork generated by hbm2java
 */
@Entity
@Table(name = "socialNetwork", schema = "public")
public class SocialNetwork implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int socialNetworkId;
	private String latinName;
	private String arabicName;
	private String networkType;
	private Collection<Structure> structures;

	public SocialNetwork() {
	}

	public SocialNetwork(int socialNetworkId) {
		this.socialNetworkId = socialNetworkId;
	}

	public SocialNetwork(int socialNetworkId, String latinName,
			String arabicName, String networkType, Set<Structure> structures) {
		this.socialNetworkId = socialNetworkId;
		this.latinName = latinName;
		this.arabicName = arabicName;
		this.networkType = networkType;
		this.structures = structures;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "socialNetworkId", unique = true, nullable = false)
	public int getSocialNetworkId() {
		return this.socialNetworkId;
	}

	public void setSocialNetworkId(int socialNetworkId) {
		this.socialNetworkId = socialNetworkId;
	}

	@Column(name = "latinName", length = 254)
	public String getLatinName() {
		return this.latinName;
	}

	public void setLatinName(String latinName) {
		this.latinName = latinName;
	}

	@Column(name = "arabicName", length = 254)
	public String getArabicName() {
		return this.arabicName;
	}

	public void setArabicName(String arabicName) {
		this.arabicName = arabicName;
	}

	@Column(name = "networkType", length = 254)
	public String getNetworktype() {
		return this.networkType;
	}

	public void setNetworktype(String networkType) {
		this.networkType = networkType;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "socialNetworks")
	public Collection<Structure> getStructures() {
		return this.structures;
	}

	public void setStructures(Collection<Structure> structures) {
		this.structures = structures;
	}

}
