package org.cni.intranet.entities;

// Generated 20 nov. 2014 12:28:53 by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * SubPositionId generated by hbm2java
 */
@Embeddable
public class SubPositionId implements Serializable {

	private int positionId;
	private int subPositionId;

	public SubPositionId() {
	}

	public SubPositionId(int positionId, int subPositionId) {
		this.positionId = positionId;
		this.subPositionId = subPositionId;
	}

	@Column(name = "positionId", nullable = false)
	public int getPositionId() {
		return this.positionId;
	}

	public void setPositionId(int positionId) {
		this.positionId = positionId;
	}
	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "subPositionId", nullable = false)
	public int getSubPositionId() {
		return this.subPositionId;
	}

	public void setSubPositionId(int subPositionId) {
		this.subPositionId = subPositionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubPositionId))
			return false;
		SubPositionId castOther = (SubPositionId) other;

		return (this.getPositionId() == castOther.getPositionId())
				&& (this.getSubPositionId() == castOther.getSubPositionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPositionId();
		result = 37 * result + this.getSubPositionId();
		return result;
	}

}
